// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbZutijVOfMb8YF53et2HiZUq_1xVtdpE',
    appId: '1:127157532951:web:669f2bbbaf2e51323e9f52',
    messagingSenderId: '127157532951',
    projectId: 'ecommerce-bloc-6dd81',
    authDomain: 'ecommerce-bloc-6dd81.firebaseapp.com',
    storageBucket: 'ecommerce-bloc-6dd81.firebasestorage.app',
    measurementId: 'G-CQYNB67Y0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyru1XyjLkaBo5zuyQLybvN2RtODyHuEE',
    appId: '1:127157532951:android:8e4294da9985cc763e9f52',
    messagingSenderId: '127157532951',
    projectId: 'ecommerce-bloc-6dd81',
    storageBucket: 'ecommerce-bloc-6dd81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrBztujZQnDCGGN8rv4bjfhcRhx2IRJ4E',
    appId: '1:127157532951:ios:ef11cdce5276b7043e9f52',
    messagingSenderId: '127157532951',
    projectId: 'ecommerce-bloc-6dd81',
    storageBucket: 'ecommerce-bloc-6dd81.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceBloc',
  );
}
